### ISSUE TITLE
.NET Core UploadFiles fails

### ISSUE THREAD

**Issue by CrustyJew** [hgupta9/FluentFTP#118]
Using `UploadFiles` under .NET Core doesn't appear to work correctly. It looks like it recognizes the file doesn't exist, tries to reset EPSV for some reason (I'm not all that familiar with FTP protocols), and then because the file doesn't exist and it didn't read in the command, it tries to use PASV instead and breaks.

```CSHARP
using(var ftp = new FluentFTP.FtpClient(profile.FtpServer, profile.FtpUsername, profile.FtpPassword)) {
                    ftp.Port = profile.FtpPort;
                    //ftp.Connect();
                    ftp.UploadFiles(files, profile.DropoffPath, FluentFTP.FtpExists.NoCheck, false, FluentFTP.FtpVerify.None, FluentFTP.FtpError.Throw);
                    //ftp.Disconnect();
                    foreach(var file in files) {
                        file.Delete();
                    }
                }

```

Exception:

`"Malformed PASV response: Entering Extended Passive Mode (|||28344|)."`

```
230 Login OK. Proceed.
FEAT
211-Features supported:
 COMB target;source_list
 REST STREAM
 SIZE
 MDTM
 XCRC filename;start;end
 SSCN
 MLST Size*;Modify*;Create;Type*;Unique;Perm*;Lang;Media-Type;CharSet;
 MODE Z
 XNOP
211 END
Text encoding: System.Text.ASCIIEncoding
SYST
215 UNIX Type: L8
Auto-detected UNIX parser
TYPE I
200 Type set to I.
EPSV
229 Entering Extended Passive Mode (|||28927|).
NLST /
150 Opening ASCII mode data connection for file list.
Disposing FtpSocketStream...
TYPE I
226 Transfer complete. 0 bytes transferred. 0 bps.
SIZE /CDALGONA20170605.RPT
200 Type set to I.
EPSV
550 /CDALGONA20170605.RPT: No such file.
PASV
229 Entering Extended Passive Mode (|||29081|).
Upload Failure for (Removed path to file): FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> FluentFTP.FtpException: Malformed PASV response: Entering Extended Passive Mode (|||29081|).
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenWrite(String path, FtpDataType type)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions)
   at FluentFTP.FtpClient.UploadFiles(IEnumerable`1 localPaths, String remoteDir, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, FtpError errorHandling)
Disposing FtpClient object...
There is stale data on the socket, maybe our connection timed out. Re-connecting.
The data was:
227 Entering Passive Mode (209,74,236,48,113,210).
```

**Comment by hgupta9** [comment]
Are you testing on a Windows or Unix machine? I know your server is Unix... And try not using "FtpExists.NoCheck", use "Skip" or "Overwrite"...

**Comment by CrustyJew** [comment]
It's running from a Windows machine. I originally tried "Overwrite" as well and that didn't work which is when I flipped it to none to see if it would make a difference.

**Comment by hgupta9** [comment]
I have improved logging of FTP commands and API calls (see [here for sample](https://github.com/hgupta9/FluentFTP/issues/106#issuecomment-306739610)) and this should help us debug exactly where the problem is.

Can you download and test with this version? 

- [FluentFTP_17.4.3_BETA2.zip](https://we.tl/QsD5EaMUql)

**Comment by hgupta9** [comment]
I made an update, please use it and run your same code again and send the logs.

- [FluentFTP_17.4.3_BETA3.zip](https://we.tl/faVqX8YWRA)

**Comment by CrustyJew** [comment]
I'll test this tomorrow morning when I have another batch of files to send. Thanks

**Comment by hgupta9** [comment]
When you test it please use the latest nuget... I have pushed the beta versions to nuget as a final release.

**Comment by CrustyJew** [comment]
testing this out this morning with 17.4.4

**Comment by CrustyJew** [comment]
This appears to be working correctly now. Thanks for the fix!

**Comment by hgupta9** [comment]
Glad to know its working. Your welcome.

**Comment by CrustyJew** [comment]
It looks like there is still some issue with it although I think the actual upload issue has to do with the FTP server. I've had issues with their server in the past, but it appears to still be making a switch to PASV incorrectly and erroring out

```
# OpenWrite("/TESTFILE.RPT", Binary)
Command:  TYPE I
Response: 226 Transfer complete. 0 bytes transferred. 0 bps.

# GetFileSize("/TESTFILE.RPT")
Command:  SIZE /TESTFILE.RPT
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "STOR /TESTFILE.RPT", 0)
Command:  EPSV
Response: 550 /TESTFILE.RPT: No such file.

# OpenPassiveDataStream(PASV, "STOR /TESTFILE.RPT", 0)
Command:  PASV
Response: 229 Entering Extended Passive Mode (|||29584|).
Error:    Upload Failure for \\server\share\TESTFILE.RPT: FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> FluentFTP.FtpException: Malformed PASV response: Entering Extended Passive Mode (|||29584|).
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenWrite(String path, FtpDataType type)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions)
   at FluentFTP.FtpClient.UploadFiles(IEnumerable`1 localPaths, String remoteDir, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, FtpError errorHandling)

# Dispose()
Status:   Disposing FtpClient object...
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
The data was: 227 Entering Passive Mode
```

**Comment by hgupta9** [comment]
No such file? The server is meant to _create_ the file since the STOR command is sent...
```
# OpenPassiveDataStream(AutoPassive, "STOR /TESTFILE.RPT", 0)
Command:  EPSV
Response: 550 /TESTFILE.RPT: No such file.
```

Anyways you can try one of the passive modes:

- Option 1. `client.DataConnectionType = FtpDataConnectionType.PASV`
- Option 2. `client.DataConnectionType = FtpDataConnectionType.EPSV`
