### ISSUE TITLE
PlatformNotSupported Exception in async operations on Windows for .net core projects

### ISSUE THREAD

**Issue by KshitizGIT** [hgupta9/FluentFTP#142]
I am getting PlatformNotSupportedException when calling any async function in a .NETCore1.1 App

**Comment by hgupta9** [comment]
Are you using the latest from nuget?

**Comment by KshitizGIT** [comment]
I was using the 17.5.8 version. But I see the latest version is 17.5.9. I will check the async functions on that version

**Comment by hgupta9** [comment]
No thats ok. Don't need to update.

**Comment by hgupta9** [comment]
Can you build a debug version of FluentFTP (or if its hard I can send you a debug version) and see which line of code this error comes in? AFAIK there is no locking in the .net core version so async should be supported.

**Comment by KshitizGIT** [comment]
yes. please do send me a debug version. I will try to debug on my end too :D

**Comment by hgupta9** [comment]
Please check:

- [FluentFTP_17.59_Debug.zip](https://we.tl/Oeozecmyqf)

**Comment by KshitizGIT** [comment]
I am still getting error using the debug version

**Comment by KshitizGIT** [comment]
This is the stacktrace

   at FluentFTP.FtpClient.AsyncConnect.BeginInvoke(AsyncCallback callback, Object object)
   at FluentFTP.FtpClient.BeginConnect(AsyncCallback callback, Object state) in D:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_Connection.cs:line 1214
   at FluentFTP.FtpClient.<ConnectAsync>b__151_0(AsyncCallback c, Object s) in D:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_Connection.cs:line 1239
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
   at FluentFTP.FtpClient.<ConnectAsync>d__151.MoveNext() in D:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_Connection.cs:line 1238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GbdOms.Common.Ftp.FtpAccess.<TestConnectionAsync>d__2.MoveNext() in F:\Projects\universal-datahub\source\OrderManagementSystem\GbdOrderManagementSystemSolution\GbdOms.Common.Ftp\FtpAccess.cs:line 30

**Comment by hgupta9** [comment]
Please see https://github.com/hgupta9/FluentFTP/issues/127

Unfortunately until the async methods are completely rewritten this will not be supported on .NET Core. I guess I'll just disable the async methods from the .NET core build.
