### ISSUE TITLE
Issue with Upload files with Flag createRemoteDirectory true

### ISSUE THREAD

**Issue by myogendra** [hgupta9/FluentFTP#157]
I am uploading a folder with nested files and folders, so while calling Upload file like:
`client.UploadFile(fileInfo.FullName, remoteRelativePath,  FtpExists.Append, true)`

I am getting an exception :
```
FluentFTP.FtpCommandException: Directory already exists
   at FluentFTP.FtpClient.CreateDirectory(String path, Boolean force)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   at FluentFTP.FtpClient.Upload(Stream fileStream, String remotePath, FtpExists existsMode, Boolean createRemoteDir)
```
As you can see I have set the flag for **CreateRemoteDirectory** to true, So for the files under this directory I am getting this error and that file is being skipped from upload.

I did a workaround like first I will create whole directory structure at FTP by loop through and then calling the uploadFile method in loop where I am passing file path of both source and destination.

Is there any way to fix this issue because I don't like this workaround, it should be very cleaner.

**Comment by hgupta9** [comment]
That's a good find. We'll try to fix it and get back to you.

**Comment by hgupta9** [comment]
Similar to https://github.com/hgupta9/FluentFTP/issues/132

**Comment by hgupta9** [comment]
Sorry this is not yet possible. UploadFile, as the name implies can only be used to upload a FILE, not a DIRECTORY. We have not implemented recursive uploading anywhere. Maybe we can add a new method UploadDirectory that will do this...

**Comment by hgupta9** [comment]
See https://github.com/hgupta9/FluentFTP/issues/161
