### ISSUE TITLE
FTPS client not working on vsftpd

### ISSUE THREAD

**Issue by aelassas** [hgupta9/FluentFTP#31]
Hello,

I've created an FTPS server on ubuntu by following this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-vsftpd-to-use-ssl-tls-on-an-ubuntu-vps).

I've tested it on Filezilla by using explicit encryption. Everything works fine. 

But when I test it with FluentFTP by using explicit encryption, I get the following error when the client is trying to connect to the remote FTPS server:

`
Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host
`

Can you please help me to solve this issue?

Kind regards,

**Comment by hgupta9** [comment]
Can you provide your login details in order for me to test? If not then can you create a test FTP account on your server and provide that? Its really difficult to debug such use-case issues without connecting to the actual server. You could just add a comment with it, and delete the comment immediately after. I will get the details by email. I will need the server hostname/IP, the user name and the password.

**Comment by aelassas** [comment]
Hi,

I've set up an ftps accounting for you to test.

Host: spreadbs.ddns.net
Port: 21
Encryption: Explicit
User: ftpuser
Pass: password

FileZilla connects successfully. It cannot list directory content but it's not a problem since it connects. Here are FileZilla logs:

Status: Address resolution for spreadbs.ddns.net
Status: Connection to 105.155.158.142:21 ...
Status of the company:
Response: 220 (vsFTPd 3.0.3)
Order: AUTH TLS
Response: 234 Carry out the negotiation.
Status: Initializing TLS ...
Status: Certificate Verification ...
Command: USER ftpuser
Status: TLS / SSL connection established.
Answer: 331 Please specify the password.
Order: PASS ********
**Answer: 230 Successful connection.**
Status: The server does not support non-ASCII characters.
Order: PBSZ 0
Answer: 200 PBSZ set to 0.
Order: PROT P
Answer: 200 PROT now Private.
**Status: Connected**
Status: Retrieving folder contents ...
Command: PWD
Answer: 257 "/" is the current directory
Order: TYPE I
Answer: 200 Switch to binary mode.
Order: PASV
Answer: 227 Switch to passive mode (192, 168, 1, 15, 167, 10).
Status: The server sent a passive response with a non-routable address. Address replaced by server.
Command: LIST
Error: Connection of data can not be established: ECONNREFUSED - Connection refused by the server


But with FluentFtp, I get this error when It tries to connect to the remote FTPS server.

Here is the code I'm using for testing:

FtpClient client = new FtpClient();
client.Host = "spreadbs.ddns.net";
client.Port = 21;
client.Credentials = new NetworkCredential("ftpuser", "password");
client.EncryptionMode = FtpEncryptionMode.Explicit;

client.Connect();


Here is the error:


**Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host**

at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
at FluentFTP.FtpClient.Connect()

Kind regards,

**Comment by hgupta9** [comment]
Fantastic. I'll test it today and let you know if I can fix this. Since I have a test account it should be easier to debug.

**Comment by hgupta9** [comment]
I'm testing this right now. Will get back to you once I configure FTPS. Since I'm not the original author of the lib and I've never used FTPS before, I'll have to figure it out myself!

**Comment by hgupta9** [comment]
I cannot list files with `GetListing()` since it simply times out waiting for a reply. I could connect however, here is the code I used:

```csharp
static void TestNameListingFTPS() {
	using (FtpClient cl = new FtpClient()) {

		cl.Credentials = new NetworkCredential(m_user, m_pass);
		cl.Host = m_host;
		cl.ValidateCertificate += OnValidateCertificate;
		cl.DataConnectionType = FtpDataConnectionType.PASV;
		cl.EncryptionMode = FtpEncryptionMode.Explicit;
		cl.Connect();

		//Console.WriteLine("Sleeping for 10 seconds to force timeout.");
		//Thread.Sleep(10000);

		foreach (FtpListItem item in cl.GetListing()) {
			Console.WriteLine(item.FullName);
			//Console.WriteLine(item.Modified.Kind);
			//Console.WriteLine(item.Modified);
		}
	}
}
static void OnValidateCertificate(FtpClient control, FtpSslValidationEventArgs e) {
	e.Accept = true;
}
````

And here are the logs:

> InterNetwork: 105.154.31.119
> 220 (vsFTPd 3.0.2)
> **AUTH TLS**
> 234 Proceed with negotiation.
> Time to activate encryption: 0h 0m 0s, Total Seconds: 0.8736015.
> USER ftpuser
> 331 Please specify the password.
> PASS <omitted>
> **230 Login successful.**
> PBSZ 0
> 200 PBSZ set to 0.
> PROT P
> 200 PROT now Private.
> FEAT
> 211-Features:
>  AUTH TLS
>  EPRT
>  EPSV
>  MDTM
>  PASV
>  PBSZ
>  PROT
>  REST STREAM
>  SIZE
>  TVFS
>  UTF8
> 211 End
> Text encoding: System.Text.UTF8Encoding
> OPTS UTF8 ON
> 200 Always in UTF8 mode.
> PWD
> 257 "/"
> PWD
> 257 "/"
> The thread '<No Name>' (0xadc) has exited with code 0 (0x0).
> TYPE I
> 200 Switching to Binary mode.
> PASV
> 227 Entering Passive Mode (192,168,1,16,250,43).
> .....

**Comment by aelassas** [comment]
Hello,

I've just tested again with your code but I'm still having the same error. I'm using FluentFTP 16.0.12 wich I downloaded from [here](https://github.com/hgupta9/FluentFTP/releases).

I solved the LIST issue on the FTPS server. Now you can list and upload files to /public/.

Could you upload the DLL that you're using to /public/ folder on the FTPS server so I can test with it. 

I'm using Visual Studio 2010 and .NET Framework 4.0.

Kind regards,

**Comment by hgupta9** [comment]
Releases is very old. Download from Nuget. Download the nuget.exe client and then open command prompt:

`nuget Install FluentFTP`

**Comment by hgupta9** [comment]
Alright, I updated the releases page. See https://github.com/hgupta9/FluentFTP/releases
Download the latest and see if your issues persist.

**Comment by aelassas** [comment]
Hi,

I've tested with the new release and I'm still having the same error.

Here is the code I'm using for testing:

```cs
class Program
    {
        static void Main(string[] args)
        {
            const string m_host = "spreadbs.ddns.net";
            const string m_user = "ftpuser";
            const string m_pass = "password";

            using (FtpClient cl = new FtpClient())
            {
                cl.Credentials = new NetworkCredential(m_user, m_pass);
                cl.Host = m_host;
                cl.ValidateCertificate += OnValidateCertificate;
                cl.DataConnectionType = FtpDataConnectionType.PASV;
                cl.EncryptionMode = FtpEncryptionMode.Explicit;
                cl.Connect();

                //Console.WriteLine("Sleeping for 10 seconds to force timeout.");
                //Thread.Sleep(10000);

                foreach (FtpListItem item in cl.GetListing())
                {
                    Console.WriteLine(item.FullName);
                    //Console.WriteLine(item.Modified.Kind);
                    //Console.WriteLine(item.Modified);
                }
            }
        }

        static void OnValidateCertificate(FtpClient control, FtpSslValidationEventArgs e)
        {
            e.Accept = true;
        }
    }
```

Here is the error I'm having:

```
System.IO.IOException 

Unable to read transport connection data: An existing connection has become closed by the remote host

at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
at FluentFTP.FtpClient.Connect()
```

Regards,

**Comment by hgupta9** [comment]
I've attached a version of the FluentFTP library and test project that works for me. Just open the solution and run it and see if you can connect. Perhaps your .NET Framework version or something else is getting in the way. If even _this_ does not work, then it must be a local issue, ie the server is rejecting your IP or your NAT/firewall/network is getting in the way. Hope this works for you.

[FluentFTP_FTPS_Test.zip](https://github.com/hgupta9/FluentFTP/files/721312/FluentFTP_FTPS_Test.zip)

This is the log I'm getting. (Output window) You should get a similar output.

	InterNetwork: 105.158.52.29
	220 (vsFTPd 3.0.2)
	AUTH TLS
	234 Proceed with negotiation.
	Time to activate encryption: 0h 0m 0s, Total Seconds: 0.4368008.
	USER ftpuser
	331 Please specify the password.
	PASS <omitted>
	230 Login successful.
	PBSZ 0
	200 PBSZ set to 0.
	PROT P
	200 PROT now Private.
	FEAT
	211-Features:
	 AUTH TLS
	 EPRT
	 EPSV
	 MDTM
	 PASV
	 PBSZ
	 PROT
	 REST STREAM
	 SIZE
	 TVFS
	 UTF8
	211 End
	Text encoding: System.Text.UTF8Encoding
	OPTS UTF8 ON
	200 Always in UTF8 mode.
	PWD
	257 "/"
	PWD
	257 "/"
	TYPE I
	200 Switching to Binary mode.
	EPSV
	229 Entering Extended Passive Mode (|||64224|).
	InterNetwork: 105.158.52.29
	LIST /
	150 Here comes the directory listing.
	Time to activate encryption: 0h 0m 0s, Total Seconds: 0.2184004.
	drwxr-xr-x    2 1001     1001         4096 Jan 21 12:23 public
	226 Directory send OK.
	Disposing FtpSocketStream...
	public
	Disposing FtpClient object...
	QUIT
	221 Goodbye.
	Disposing FtpSocketStream...
	The thread 'vshost.RunParkingWindow' (0x1318) has exited with code 0 (0x0).
	The thread '<No Name>' (0x1330) has exited with code 0 (0x0).
	Disposing FtpSocketStream...

**Comment by hgupta9** [comment]
Can you check with the code I provided?

**Comment by aelassas** [comment]
Hi,

I tested with the code that you provided and I'm still having the same error at FtpSocketStream.cs line 680 (m_sslStream.AuthenticateAsClient).

Can you please test again?

Here are the details of the error:

```
System.IO.IOException
Unable to read transport connection data: An existing connection had to be closed by the remote host.

at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols) dans C:\dev\FluentFTP\FluentFTP\FtpSocketStream.cs:ligne 680
at FluentFTP.FtpClient.Connect() dans C:\dev\FluentFTP\FluentFTP\FtpClient.cs:ligne 854
at Tests.Program.TestNameListingFTPS() dans C:\dev\FluentFTP\FluentFTP.Tests\Program.cs:ligne 546
at Tests.Program.Main(String[] args) dans C:\dev\FluentFTP\FluentFTP.Tests\Program.cs:ligne 65
```

Regards,

**Comment by hgupta9** [comment]
Since it works on my end and not on your PC, it seems to be a local issue. Disable/uninstall any firewall or antivirus program. Also check if the FTP host has blacklisted your IP / IP range. There seems to be nothing I can do atm.
