### ISSUE TITLE
DownloadFile throws exceptions in some cases

### ISSUE THREAD

**Issue by picaosgeo** [hgupta9/FluentFTP#57]
In the document, Download method described 
"Downloads a file from the server to the local file system. Returns true if succeeded, false if failed or file does not exist. ".

But "DownloadFile(localPath, remotePath)" raise error exception when the remotePath dose not exist.

> Error: FluentFTP.FtpException: Error while downloading the file from the server.See InnerException for more info. ---> FluentFTP.FtpCommandException: Command not implemented
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart)
   at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream)

**Comment by picaosgeo** [comment]
I found this error caused by "OPTS UTF8+ON" COMMAND.
How to disable this command to send to FTP Server?

FluentFTP.FtpClient.DisableUTF8() can not disable this and re-send "OPTS UTF8+OFF" to the server...

**Comment by hgupta9** [comment]
@picaosgeo I have found the issue. Calling `DisableUTF8()` should work in the next release.

**Comment by hgupta9** [comment]
Tell me if it worked and I will close the issue accordingly.

**Comment by hgupta9** [comment]
I added a note into the docs saying that exceptions will be thrown for critical errors.
